fix code blocks bug
pixie-labs/pixie-docs pull request #24
Opened 2021-04-23 14:02 UTC by postescu

2021-04-23 22:55 UTC, htroisi commented
This fixes https://github.com/pixie-labs/pixie-docs/issues/6.

2021-04-25 06:24 UTC, htroisi requested changes
LGTM

2021-04-26 06:46 UTC, htroisi approved these changes

2021-04-29 03:30 UTC, aimichelle approved these changes

2021-05-04 02:33 UTC, merged